name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Download dependencies
      run: go mod download
      
    - name: Run tests
      run: go test ./...
      
    - name: Build application
      run: go build -o linkwatch cmd/main.go
      
    - name: Test Docker build
      run: docker build -t linkwatch .